automation: fix fedora builds
using dnf-utils instead of yum-utils on Fedora.
Latest Fedoras uses boolean conditionals, so yum-builddep would fail
with something like:
  Error: Package: cmake-rpm-macros-3.10.1-11.fc27.noarch (fedora-updates-fc27)
            Requires: (cmake-data = 3.10.1-11.fc27 if cmake-data < 3.10.1-11.fc27)
  Error: Package: cmake-rpm-macros-3.10.1-11.fc27.noarch (fedora-updates-fc27)
            Requires: (cmake = 3.10.1-11.fc27 if cmake < 3.10.1-11.fc27)

dnf-util provides symlinks allowing to keep using yum-builddep command
also with dnf.

Change-Id: I08102b8bdf056b1662ab530d1c1d291be84e6ee6
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>